#!/bin/bash

environment=$1
projName="ecustos"

function precheck() {
    #[ "${environment}" == "" ] && environment="stage"
    if [ "${environment}" == "prod" ]; then
        region="us-east-1"
    elif [ "${environment}" == "stage" ]; then
        region="us-west-2"
    else
        usage
        exit 1
    fi

    [ -f /tmp/pipeline.LOCK ] && echo -e "Pipeline ja em execucao!\nSe voce deseja executar este script mesmo assim delete o arquivo /tmp/pipeline.LOCK" && exit

    [ -f ~/.aws/config ] && chkProfile=`cat ~/.aws/config | grep profile | grep ${projName}`
    if [ "${chkProfile}" != "" ]; then
        profileName="--profile ${projName}"
    else
        profileName=""
    fi

    set -e
    aws ${profileName} autoscaling describe-scaling-activities  --region us-west-2 --max-items 50 | jq '.Activities[].StatusCode' > /tmp/activity-status
    for status in `cat /tmp/activity-status | cut -d "\"" -f2`; do
        if [ "${status}" != "Successful" ] && [ "${status}" != "Failed" ]; then 
             echo -e "Pipeline ainda em execuçao!\nAguarde até que todas as atividades do autoscaling estejam finalizadas.\nVoce pode verificar o status do autoscaling diretamente no painel da AWS." && exit
        fi
    done
    rm -f /tmp/activity-status

    aws ${profileName} autoscaling describe-auto-scaling-groups --region ${region} | jq > /tmp/autoscalingGroup
    set +e

    [ -f /tmp/afterAsgIncrease ] && rm /tmp/afterAsgIncrease
    [ -f /tmp/instanceList ] && rm /tmp/instanceList
    [ -f /tmp/afterAsgIncrease ] && rm /tmp/afterAsgIncrease

    touch /tmp/pipeline.LOCK
}

function usage() {
    echo ""
    echo "Usage:"
    echo "${0} <environment>"
    echo "Ex.: pipeline stage"
    echo ""
}

function chkInstance() {
    asgInstance=`cat /tmp/autoscalingGroup | jq '.AutoScalingGroups[0].Instances[] | "\(.InstanceId)_\(.HealthStatus)_\(.LaunchTemplate.Version),"' | cut -d "\"" -f2`

    for healthy in `echo ${asgInstance}`; do
        instanceId=`echo ${healthy} | cut -d "_" -f1`
        version=`echo ${healthy} | cut -d "_" -f3 | cut -d "," -f1`
        healthy=`echo ${healthy} | cut -d "_" -f2`
        if [ "${healthy}" == "Healthy" ]; then
            echo ${instanceId} >> /tmp/instanceList
        fi
    done

    [ -f /tmp/instanceList ] && cat /tmp/instanceList
}

function updateSize() {
    asgName=`cat /tmp/autoscalingGroup | jq '.AutoScalingGroups[0].AutoScalingGroupName' | cut -d "\"" -f2`
    minSize=`cat /tmp/autoscalingGroup | jq '.AutoScalingGroups[0].MinSize'`
    maxSize=`cat /tmp/autoscalingGroup | jq '.AutoScalingGroups[0].MaxSize'`
    desiredCapacity=`cat /tmp/autoscalingGroup | jq '.AutoScalingGroups[0].DesiredCapacity'`
    
    [ "${minSize}" == "" ] && exit 1
    [ "${maxSize}" == "" ] && exit 1
    [ "${desiredCapacity}" == "" ] && exit 1

    set -e
    minSize=`expr ${minSize} "*" 2`
    maxSize=`expr ${maxSize} "*" 2`
    desiredCapacity=`expr ${desiredCapacity} "*" 2`
    
    aws ${profileName} autoscaling update-auto-scaling-group --auto-scaling-group-name ${asgName} --min-size ${minSize} --max-size ${maxSize} --desired-capacity ${desiredCapacity} --region ${region}
    set +e
}

function checkAfterIncrease() {
    sleep 60
    aws ${profileName} autoscaling describe-auto-scaling-groups --region ${region} | jq > /tmp/afterAsgIncrease
    
    newInstanceId=`cat /tmp/afterAsgIncrease | jq '.AutoScalingGroups[0].Instances[] | "\(.InstanceId)_\(.HealthStatus)_\(.LaunchTemplate.Version),"' | cut -d "\"" -f2 | grep -v Healthy`
}

function deleteInstances() {
    instanceIds=`cat /tmp/instanceList | tr "\n" " "`

    for instanceIdDelete in ${instanceIds}; do
        aws ${profileName} autoscaling terminate-instance-in-auto-scaling-group --region ${region} --instance-id ${instanceIdDelete} --no-should-decrement-desired-capacity
    done
    echo "Delete instance done!"
}

function decreaseSize() {
    set -e
    minSize=`expr ${minSize} "/" 2`
    maxSize=`expr ${maxSize} "/" 2`
    desiredCapacity=`expr ${desiredCapacity} "/" 2`

    aws ${profileName} autoscaling update-auto-scaling-group --auto-scaling-group-name ${asgName} --min-size ${minSize} --max-size ${maxSize} --desired-capacity ${desiredCapacity} --region ${region}
    echo "Decrease done!"
    set +e
}

precheck

if [ "${environment}" == "prod" ] || [ "${environment}" == "stage" ];then
    chkInstance
    updateSize
    checkAfterIncrease

    count=0
    while [ "${count}" -lt 5 ]; do
        if [ "${newInstanceId}" != "" ]; then 
            echo "Waiting health check..."
            delete="ko"
            checkAfterIncrease
        else
            delete="ok"
            echo ${delete}
            break
        fi
        ((++count))
    done

    [ "${delete}" != "ok" ] && echo "Time out!" && exit 1

    deleteInstances
    decreaseSize

    rm -f /tmp/pipeline.LOCK

    echo "Done!"
else
    usage
fi

# fazer: check numero desired size comparando com numero de instancias