name: Container Workflow

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_STAGING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_STAGING }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_STAGING }}

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    container:
      image: xueshanf/awscli:alpine-3.11
    env: 
      EC2_TAG: instance-ecustos-stage
    steps:
      - name: Run Commands
        run: |
          ssh --help
          git clone https://github.com/lpolone/stellar.git --branch stage
          cd stellar
          git config --global user.email "test@example.com"
          git config --global user.name "test"
          git remote add test ssh://ecustos-stg:/var/www/test.git
          git push test stage:master
         
