name: Container Workflow

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_STAGING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_STAGING }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_STAGING }}

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    container:
      image: xueshanf/awscli:latest
    env: 
      EC2_TAG: instance-ecustos-stage
    steps:
      - name: Run Commands
        run: |
          # cloning project
          cd  ~/
          git clone https://github.com/lpolone/stellar.git --branch stage
          cd stellar
          chmod 400 ~/stellar/key-ecustos-stage.pem

          # configuring ssh
          mkdir -p ~/.ssh
          chmod 600 -R ~/.ssh
          echo "Host ecustos-stg" >> ~/.ssh/config
          echo "HostName 54.71.62.169" >> ~/.ssh/config
          echo "User ecustos" >> ~/.ssh/config
          echo "Port 22" >> ~/.ssh/config
          echo "IdentityFile ~/stellar/key-ecustos-stage.pem" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          cat ~/.ssh/config

          #echo "54.71.62.169  ecustos-stg" >> /etc/hosts
          
          # configuring remote
          #git config --global user.email "test@example.com"
          #git config --global user.name "test"
          #git remote add test ssh://ecustos-stg:/var/www/test.git
          #git push test stage:master
          
          apk add openssh
          ssh ecustos-stg