name: Container Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xueshanf/awscli:alpine-3.11

    steps:
      - name: Run Commands
        run: |
              echo pippo
