name: Container Workflow

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_STAGING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_STAGING }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_STAGING }}

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage
    container:
      image: xueshanf/awscli:alpine-3.11
    env: 
      EC2_TAG: instance-ecustos-stage
    steps:
      - name: Run Commands
        run: |
          aws ec2 describe-instances --filters "Name=tag:Name,Values=$EC2_TAG" "Name=instance-state-name,Values=running"  --output text --query 'Reservations[*].Instances[*].[PublicIpAddress]' > aws_ips.txt
          echo -e "\nLista de IPs\n"; cat aws_ips.txt && chmod +x test.sh && ./test.sh
