name: Container Workflow

stage:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_STAGING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_STAGING }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_STAGING }}

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
#    environment: stage
    container:
      image: xueshanf/awscli:alpine-3.11 
    steps:
      - name: Run Commands
        run: |
              echo $AWS_DEFAULT_REGION
              echo $AWS_ACCESS_KEY_ID
              echo $AWS_SECRET_ACCESS_KEY

